version: '3.11'

services:

  redis:
    image: redis:7.0.11-alpine

  django:
    image: django-docker:0.0.1
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery:
    image: celery-docker:0.0.1
    build: .
    ports:
      - "8001:8000"
    depends_on:
      - redis

  celery2:
    image: celery2-docker:0.0.1
    build:
      context: ./celeryworker
      dockerfile: Dockerfile
    command: celery -A celery worker -l INFO -Q celery, celery:1, celery:2, celery:3
    ports:
      - "8001:8000"
    depends_on:
      - redis
      - djnago
